name: JSConverter
main: FellOp\JSConverter
version: 1.0.0
api: [1.0.0]
load: STARTUP
author: FellOp
description: Plugin for making phar from js.
website: http://githib.com/FellOp/JSConverter

commands:
  description: /conv
  usage: "Usage: /conv <script name>"
  permission: fellop.conv

permissions:
 fellop.conv:
  description: "Make phar from js"
  default: op
